### ISSUE TITLE
Bele bele

### ISSUE THREAD

**Issue by HolyJambalaya** [HackerLacker/SkyWarsStats#2]

**Comment by HolyJambalaya** [comment]
![image](https://github.com/HackerLacker/SkyWarsStats/assets/148009396/7488238f-cc3a-4e28-9c2a-0d50dcabda5f)

**Comment by HolyJambalaya** [comment]
![image](https://github.com/HackerLacker/SkyWarsStats/assets/148009396/34920508-5054-4e35-8423-f3769f3d1a6c)

**Comment by Nishimara** [comment]
💊

**Comment by HolyJambalaya** [comment]
Ты дибил?!?!?!!???
